### ISSUE TITLE
i can not find the sample plugins in hop window

### ISSUE THREAD

**Issue by Constantine9527** [project-hop/hop-plugin-sample#2]
Hi, I clone this code and run it, but i can not find the sample plugins in hop , I think there should be 2 plugins in hop , transform: sample, action: sample, but they are not there. 
This is hop window：
![image](https://user-images.githubusercontent.com/20188341/173482012-034b0148-2e14-4df4-ae2a-ab5b2ab4566d.png)

this is my run configuration：
![image](https://user-images.githubusercontent.com/20188341/173482173-ed913607-ecfd-4ce5-9ed7-5041e15a7788.png)

this is the assemblies/debug/target/hop-assemblies-debug-2.0.0-SNAPSHOT folder：
![image](https://user-images.githubusercontent.com/20188341/173482392-6548d393-1282-4a56-baaa-cc82f4e96767.png)

I'm such a fool, I forgot to create pipeline ! :(

**Comment by hansva** [comment]
glad it works as expected ;) but indeed you need to create a workflow or pipeline to see the action/transform
