### ISSUE TITLE
cannot work on win32-64

### ISSUE THREAD

**Issue by zhangminliang** [project-hop/hop-plugin-sample#5]
it cannot work on win32-64, because the program is started using swt.linux preferentially in my win32-64 PC.
After i remove all swt.linux dependency in pom.xml and just left swt.win32. it's finally work fine.

**Comment by hansva** [comment]
I think this issue is coming from upstream, there are profiles attached to the SWT libraries to resolve the correct one.
I will try and figure out a solution

**Comment by hansva** [comment]
This issue has been resolved
